vich_uploader:
    db_driver: orm

    mappings:
        advert_photos:
            uri_prefix: '%advert_photos%'
            upload_destination: '%kernel.project_dir%/public%advert_photos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
